server:
    port: 8080
    servlet:
        context-path: /ch10

spring:
    application:
        name: ch10
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: abc1234
        url: jdbc:mysql://127.0.0.1:3306/studydb
        username: jsa7868
    devtools:
        livereload:
            enabled: true
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true

logging:
    file:
        name: logs/ch10.log
    level:
        jdbc:
            connection: info
            resultsettable: info
            sqlonly: info
            sqltiming: info
        root: info

jwt:
    issuer:m_mny1004@naver.com
    secret:qaj1sMBdWRfP4vWmPET3Th2Rpkp0TdjH